version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: sunday
    versioning-strategy: widen
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - automerge
