tasks:
  - init: mkdir -p /workspace/data
    command: mongod --quiet --dbpath /workspace/data
  - before: rm -rf .next
    init: |
      npm ci
      npm run fixtures:load
      cp .env.example .env
    command: npm run dev

image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview
