version = 1

[merge]
	method = "rebase"
	delete_branch_on_merge = true
	blocking_labels = ["wip"]

[merge.automerge_dependencies]
	versions = ["minor", "patch"]
	usernames = ["dependabot"]

[approve]
	auto_approve_usernames = ["dependabot"]

[update]
	always = true
	ignored_usernames = ["dependabot"]
