name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        eslint_flags: --ext '.js' --ext '.ts' --ext '.tsx' .

  tsc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - uses: icrawl/action-tsc@v1

  unit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    needs: [lint, tsc]
    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - uses: actions/cache@v1
      name: Cache Next.js build
      with:
        path: .next/cache
        key: ${{ runner.os }}-next-build
        restore-keys: |
          ${{ runner.os }}-next-build-
    - name: npm test
      run: |
        npm test -- --coverage
      env:
        CI: 'true'
        APP_SECRET: 4C3E89619525956BA3573B8426F6C
    - uses: actions/upload-artifact@v1
      with:
        name: unit-coverage
        path: coverage/unit

  e2e:
    runs-on: ubuntu-16.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    needs: [lint, tsc]
    services:
      mongodb:
        image: mongo:4
        ports:
        - "27017:27017"
    steps:
    - uses: actions/checkout@v2
    - name: Cache Next.js build
      uses: actions/cache@v1
      with:
        path: .next
        key: ${{ runner.os }}-next-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-next-build-
    - uses: bahmutov/npm-install@v1
    - name: Load fixtures
      run: npm run fixtures:load
      env:
        MONGODB_URL: mongodb://localhost:${{ job.services.mongodb.ports[27017] }}/admin
    - name: Cypress run
      uses: cypress-io/github-action@v1
      timeout-minutes: 10
      env:
        CODE_COVERAGE: 'true'
        MONGODB_URL: mongodb://localhost:${{ job.services.mongodb.ports[27017] }}/admin
        APP_SECRET: 4C3E89619525956BA3573B8426F6C
      with:
        build: npm run build
        start: npm start
        wait-on: 'http://localhost:3000'
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Cypress screenshots
        path: cypress/screenshots
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Cypress video
        path: cypress/videos
    - run: npx nyc report
    - uses: actions/upload-artifact@v1
      with:
        name: e2e-coverage
        path: coverage/e2e

  api:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    needs: [lint, tsc]
    services:
      mongodb:
        image: mongo:4
        ports:
        - "27017:27017"
    steps:
    - uses: actions/checkout@v2
    - name: Cache Next.js build
      uses: actions/cache@v1
      with:
        path: .next
        key: ${{ runner.os }}-next-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-next-build-
    - uses: bahmutov/npm-install@v1
    - name: Prepare, build and run
      run: |
        npm run fixtures:rebuild
        npm run build
        npm start &
        npx newman run https://api.getpostman.com/collections/367460-806c64d2-beba-4bfe-a2d6-7a346abab79d?apikey=$POSTMAN_API_KEY
      env:
        MONGODB_URL: mongodb://localhost:${{ job.services.mongodb.ports[27017] }}/admin
        APP_SECRET: 4C3E89619525956BA3573B8426F6C
        NODE_ENV: production
        POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
